return {
  cmd = { 'emmet-ls', '--stdio' },
  filetypes = {
    'html',
    'htmldjango',
    'css',
    'javascript',
    'javascriptreact',
    'typescript',
    'typescriptreact',
    'css',
    'ruby',
    'markdown',
    'javascript',
    'javascriptreact',
    'less',
    'sass',
    'scss',
    'svelte',
    'pug',
    'typescriptreact',
    'vue',
    'html.twig.js.css',
  },
  root_markers = { '.git' },
}
